name: Streamline
favicon: null
layout_spectrum: 0.9411766377743334
typography_spectrum: 0.5315606868825853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cc9900'
    - '#127012'
    - '#bdbdbd'
    - '#e5d831'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
